version: '3.8'

services:
  keycloak:
    container_name: keycloakBankApp
    image: quay.io/keycloak/keycloak:24.0.2
    volumes:
      - ./keycloak-data:/opt/keycloak/data  # ¡Esta línea es clave!
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]